version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: simplecards_dev
      POSTGRES_USER: simplecards
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  postgres_test:
    image: postgres:15
    environment:
      POSTGRES_DB: simplecards_test
      POSTGRES_USER: simplecards
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
  redis_data: